substitutions:
  device_name: atom-echo
  friendly_name: Atom Echo

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: status_listening
          brightness: 30%
          red: 0%
          green: 0%
          blue: 100%

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

light:
  - platform: esp32_rmt_led_strip
    id: status_listening
    name: "${friendly_name} Status LED"
    pin: GPIO27
    num_leds: 1
    chipset: WS2812
    rgb_order: GRB
    on_turn_on:
      - lambda: |-
          auto &cv = id(status_listening)->remote_values;
          float r = cv.get_red();
          float g = cv.get_green();
          float b = cv.get_blue();
          // Use the captured RGB values in your existing status handler.
